name: 'Action For Semantic Release'
description: 'GitHub Action for Semantic Release'
author: 'cycjimmy'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  branch:
    description: 'The branch for release'
    default: master
  extra_plugins:
    description: 'Extra plugins for pre-install'
    default: ''
  dry_run:
    description: 'Whether to run semantic release in "dry-run" mode. It will override the dryRun attribute in your configuration file'
    default: ''
outputs:
  new-release-published:
    description: 'Whether a new release was published'
runs:
  using: 'node12'
  main: 'index.js'
