name: Check Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: ./
        with:
          semantic_version: 15
          extra_plugins: |
            @semantic-release/git@7
            @semantic-release/changelog@3
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

